# Generated by Django 5.1.5 on 2025-06-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ijaradagi_kitob_infosi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
